const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
    db: {
        getSuppliers: () => ipcRenderer.invoke('db:getSuppliers'),
        addSupplier: (supplier) => ipcRenderer.invoke('db:addSupplier', supplier),
        updateSupplier: (supplier) => ipcRenderer.invoke('db:updateSupplier', supplier),
        deleteSupplier: (id) => ipcRenderer.invoke('db:deleteSupplier', id),
        getInvoices: () => ipcRenderer.invoke('db:getInvoices'),
        addInvoice: (invoice, taxLines) => ipcRenderer.invoke('db:addInvoice', { invoice, taxLines }),
        updateInvoice: (invoice, taxLines) => ipcRenderer.invoke('db:updateInvoice', { invoice, taxLines }),
        deleteInvoice: (id) => ipcRenderer.invoke('db:deleteInvoice', id),
        getDocumentTypes: () => ipcRenderer.invoke('db:getDocumentTypes'),
        addDocumentType: (docType) => ipcRenderer.invoke('db:addDocumentType', docType),
        updateDocumentType: (docType) => ipcRenderer.invoke('db:updateDocumentType', docType),
        deleteDocumentType: (id) => ipcRenderer.invoke('db:deleteDocumentType', id),
        getWithholdingTypes: () => ipcRenderer.invoke('db:getWithholdingTypes'),
        addWithholdingType: (wt) => ipcRenderer.invoke('db:addWithholdingType', wt),
        updateWithholdingType: (wt) => ipcRenderer.invoke('db:updateWithholdingType', wt),
        deleteWithholdingType: (id) => ipcRenderer.invoke('db:deleteWithholdingType', id),
        getCCDocuments: () => ipcRenderer.invoke('db:getCCDocuments'),
        addCCDocument: (doc) => ipcRenderer.invoke('db:addCCDocument', doc),
        updateCCDocument: (doc) => ipcRenderer.invoke('db:updateCCDocument', doc),
        deleteCCDocument: (id) => ipcRenderer.invoke('db:deleteCCDocument', id),
        getProvinces: () => ipcRenderer.invoke('db:getProvinces'),
        addProvince: (province) => ipcRenderer.invoke('db:addProvince', province),
        updateProvince: (province) => ipcRenderer.invoke('db:updateProvince', province),
        deleteProvince: (id) => ipcRenderer.invoke('db:deleteProvince', id),
        getMunicipalities: () => ipcRenderer.invoke('db:getMunicipalities'),
        addMunicipality: (municipality) => ipcRenderer.invoke('db:addMunicipality', municipality),
        updateMunicipality: (municipality) => ipcRenderer.invoke('db:updateMunicipality', municipality),
        deleteMunicipality: (id) => ipcRenderer.invoke('db:deleteMunicipality', id),
        getSupplierAttachments: (supplierId) => ipcRenderer.invoke('db:getSupplierAttachments', supplierId),
        addSupplierAttachment: (attachment) => ipcRenderer.invoke('db:addSupplierAttachment', attachment),
        deleteSupplierAttachment: (id) => ipcRenderer.invoke('db:deleteSupplierAttachment', id),
        getClients: () => ipcRenderer.invoke('db:getClients'),
        addClient: (client) => ipcRenderer.invoke('db:addClient', client),
        updateClient: (client) => ipcRenderer.invoke('db:updateClient', client),
        deleteClient: (id) => ipcRenderer.invoke('db:deleteClient', id),
        getClientAttachments: (clientId) => ipcRenderer.invoke('db:getClientAttachments', clientId),
        addClientAttachment: (attachment) => ipcRenderer.invoke('db:addClientAttachment', attachment),
        deleteClientAttachment: (id) => ipcRenderer.invoke('db:deleteClientAttachment', id),
        getCompanyInfo: () => ipcRenderer.invoke('db:getCompanyInfo'),
        updateCompanyInfo: (company) => ipcRenderer.invoke('db:updateCompanyInfo', company),
        getCompanyAttachments: (companyId) => ipcRenderer.invoke('db:getCompanyAttachments', companyId),
        addCompanyAttachment: (attachment) => ipcRenderer.invoke('db:addCompanyAttachment', attachment),
        deleteCompanyAttachment: (id) => ipcRenderer.invoke('db:deleteCompanyAttachment', id),
        getStaff: () => ipcRenderer.invoke('db:getStaff'),
        addStaff: (staff) => ipcRenderer.invoke('db:addStaff', staff),
        updateStaff: (staff) => ipcRenderer.invoke('db:updateStaff', staff),
        deleteStaff: (id) => ipcRenderer.invoke('db:deleteStaff', id),
        getStaffAttachments: (staffId) => ipcRenderer.invoke('db:getStaffAttachments', staffId),
        addStaffAttachment: (attachment) => ipcRenderer.invoke('db:addStaffAttachment', attachment),
        deleteStaffAttachment: (id) => ipcRenderer.invoke('db:deleteStaffAttachment', id),
        getDepartments: () => ipcRenderer.invoke('db:getDepartments'),
        addDepartment: (dept) => ipcRenderer.invoke('db:addDepartment', dept),
        updateDepartment: (dept) => ipcRenderer.invoke('db:updateDepartment', dept),
        deleteDepartment: (id) => ipcRenderer.invoke('db:deleteDepartment', id),
        getJobFunctions: () => ipcRenderer.invoke('db:getJobFunctions'),
        addJobFunction: (jf) => ipcRenderer.invoke('db:addJobFunction', jf),
        updateJobFunction: (jf) => ipcRenderer.invoke('db:updateJobFunction', jf),
        deleteJobFunction: (id) => ipcRenderer.invoke('db:deleteJobFunction', id),
        getIRTScales: () => ipcRenderer.invoke('db:getIRTScales'),
        addIRTScale: (scale) => ipcRenderer.invoke('db:addIRTScale', scale),
        updateIRTScale: (scale) => ipcRenderer.invoke('db:updateIRTScale', scale),
        deleteIRTScale: (id) => ipcRenderer.invoke('db:deleteIRTScale', id),
        getSubsidies: () => ipcRenderer.invoke('db:getSubsidies'),
        addSubsidy: (subsidy) => ipcRenderer.invoke('db:addSubsidy', subsidy),
        updateSubsidy: (subsidy) => ipcRenderer.invoke('db:updateSubsidy', subsidy),
        deleteSubsidy: (id) => ipcRenderer.invoke('db:deleteSubsidy', id),
        getRemunerationMaps: () => ipcRenderer.invoke('db:getRemunerationMaps'),
        getRemunerationMap: (id) => ipcRenderer.invoke('db:getRemunerationMap', id),
        addRemunerationMap: (map) => ipcRenderer.invoke('db:addRemunerationMap', map),
        updateRemunerationMapStatus: (id, status) => ipcRenderer.invoke('db:updateRemunerationMapStatus', { id, status }),
        deleteRemunerationMap: (id) => ipcRenderer.invoke('db:deleteRemunerationMap', id),
        getRemunerationLines: (mapId) => ipcRenderer.invoke('db:getRemunerationLines', mapId),
        addRemunerationLine: (line) => ipcRenderer.invoke('db:addRemunerationLine', line),
        updateRemunerationLine: (line) => ipcRenderer.invoke('db:updateRemunerationLine', line),
        deleteRemunerationLine: (id) => ipcRenderer.invoke('db:deleteRemunerationLine', id),
        getRemunerationLineSubsidies: (lineId) => ipcRenderer.invoke('db:getRemunerationLineSubsidies', lineId),
        addRemunerationLineSubsidy: (subsidy) => ipcRenderer.invoke('db:addRemunerationLineSubsidy', subsidy),
        deleteRemunerationLineSubsidies: (lineId) => ipcRenderer.invoke('db:deleteRemunerationLineSubsidies', lineId),
    },

    auth: {
        login: (email, password) => ipcRenderer.invoke('auth:login', { email, password }),
    }
});
